hydra:
  run:
    dir: ${oc.env:MINESTUDIO_SAVE_DIR}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra/job_logging: colorlog
hydra/hydra_logging: colorlog

dataset_dirs: 
  - '/data/contractors/dataset_6xx'
  - '/data/contractors/dataset_7xx'
  - '/data/contractors/dataset_8xx'
  - '/data/contractors/dataset_9xx'
  - '/data/contractors/dataset_10xx'

batch_size: 8
num_workers: 6
prefetch_factor: 4
split_ratio: 0.95
devices: 8
learning_rate: 0.00004
weight_decay: 0.001
warmup_steps: 2000
save_freq: 10000
ckpt_path: null
objective_weight: 0.01
shuffle_episodes: False
episode_continuous_batch: False

model:
  backbone: 'efficientnet_b0.ra_in1k'
  hiddim: 1024
  num_heads: 8
  num_layers: 4
  timesteps: 128
  mem_len: 128

ema:
  decay: 0.999
  validate_original_weights: True
  every_n_steps: 8
  cpu_offload: False
